### ISSUE TITLE
Support for SSR? 

### ISSUE THREAD

**Issue by DevanandGowda** [kybarg/react-qr-scanner#10]
I am using Gatsby which uses SSR. 

I have used a similar library `react-qr-reader` in which they have listed in known issues that it won't support SSR.

Since known issues of this library doesn't mention anything about it. I was wondering if it actually supports SSR.

**Comment by DevanandGowda** [comment]
I ended up requiring the model in `componentDidMount()`.

**Comment by j-651** [comment]
@DevanandGowda Can you provide an example of how you got around this? I am running into the I same issue with Gatsby.
