### ISSUE TITLE
[Q] : what is the difference between `JodusNodus/react-qr-reader` and this

### ISSUE THREAD

**Issue by geminiyellow** [kybarg/react-qr-scanner#3]
hi @kybarg i notice that 

> Thanks to initial repo https://github.com/JodusNodus/react-qr-reader

but  what is the difference between `JodusNodus/react-qr-reader` and this

**Comment by geminiyellow** [comment]
are you just update the build system ? or add some amazing feature ?

**Comment by kybarg** [comment]
@geminiyellow https://github.com/JodusNodus/react-qr-reader is focused on supporting mobile devices and supports newest browser APIs  while this repo is a fork for oler version and main goal is to support multiple cameras support using browsers camera ID instead of mobiles Front/Rear cameras...

**Comment by geminiyellow** [comment]
👍  thank you @kybarg

**Comment by nafg** [comment]
Can you add that to the README?
