### ISSUE TITLE
FacingMode "rear" not working on latest versions iOS (14.4.2) and Safari (14.0) for me?

### ISSUE THREAD

**Issue by tempuslight** [kybarg/react-qr-scanner#40]
I've come on a project where they have used your library and there's some last issues to fix, but one where it's specifically for your library, so I hope to find some help here.  

The problem we're facing is that iOS users complain that the "rear" camera (facingMode) isn't working. I've looked in the code, and it's pretty straightforward: they're just using a bool check on "facingMode" to determine which camera to show ("front" or "rear"). Users on Android (and myself) however can do this in Google Chrome, so the functionality/code seems correct.

I've received notice from the other people (not devs, but PM/analists etc.) on my project that this was tested, months ago, and was found to be working on iOS devices they tested on (i have no clue which versions etc).  

Can anyone help me trying to figure out how to find the issue with this problem and how to fix it? Do others also have this problem?  

I've also checked out the demo link here: https://kybarg.github.io/react-qr-scanner/?path=/story/qr-reader--choose-camera , on n iOS 14.4.2 device, latest versions etc and in this demo I however CAN change my camera, but in our app using "facingMode" it seems to not work? Is the source code of this demo example available?

**Comment by shendel** [comment]
@tempuslight try this https://github.com/kybarg/react-qr-scanner/issues/39#issuecomment-811092450
